packages:
  - packages/*
  - '!playgrounds/**'

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@formkit/drag-and-drop': ^0.5.3
    '@primeuix/themes': ^1.2.5
    '@unocss/preset-icons': ^66.5.4
    '@unocss/preset-uno': ^66.5.4
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/compiler-sfc': ^3.5.22
    '@vue/server-renderer': ^3.5.22
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^13.9.0
    '@vueuse/head': ^2.0.0
    changelogen: ^0.6.2
    chart.js: ^4.5.1
    consola: ^3.4.2
    cookie: ^1.0.2
    esbuild: ^0.25.11
    eslint: ^9.38.0
    json-editor-vue: ^0.18.1
    mkdist: ^2.4.1
    sass: ^1.93.2
    tslib: ^2.8.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.5.4
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^29.1.0
    vite: ^7.1.10
    vite-plugin-dts: ^4.5.4
    vite-plugin-eslint: ^1.8.1
    vite-plugin-pages: ^0.33.1
    vite-ssg: ^28.2.1
    vue: ^3.5.22
    vue-demi: ^0.14.10
    vue-router: ^4.6.3
    vue-sfc-transformer: ^0.1.17
    vue-tsc: ^3.1.1
  docs:
    vitepress: 2.0.0-alpha.12
  formkit:
    '@formkit/addons': ^1.6.9
    '@formkit/core': ^1.6.9
    '@formkit/i18n': ^1.6.9
    '@formkit/inputs': ^1.6.9
    '@formkit/vue': ^1.6.9
  i18n:
    '@intlify/core': ^11.1.12
    vue-i18n: ^11.1.12
  integrations:
    '@nuxt/kit': ^4.1.2
    '@nuxt/schema': ^4.1.2
  primevue:
    primeicons: ^7.0.0
    primevue: ^4.4.1
  test:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    happy-dom: ^20.0.5
    vitest: ^3.2.4
  types:
    '@types/node': ^24.8.1

shamefullyHoist: true

shellEmulator: true

sideEffectsCache: false

strictPeerDependencies: false
