packages:
  - packages/*
  - '!playgrounds/**'

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
  formkit:
    '@formkit/addons': ^1.6.9,
    '@formkit/core': ^1.6.9,
    '@formkit/i18n': ^1.6.9,
    '@formkit/inputs': ^1.6.9,
    '@formkit/vue': ^1.6.9,
  i18n:
    '@intlify/core': ^11.1.12
    vue-i18n: ^11.1.12
  primevue:
    primevue: ^4.4.1
    primeicons: ^7.0.0
  docs:
    vitepress: ^2.0.0-alpha.12
  integrations:
    '@nuxt/kit': ^4.1.2
    '@nuxt/schema': ^4.1.2
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.7.2


shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
