minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

overrides:
  '@primeuix/styled': 0.7.4
  '@primeuix/styles': 2.0.3
  '@primeuix/themes': 2.0.3
  '@primeuix/utils': 0.6.4
  '@primevue/core': 4.5.5
  '@primevue/icons': 4.5.5
  primeicons: 7.0.0
  primevue: 4.5.5

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  json-editor-vue: false
  vue-demi: false
