packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@antfu/eslint-config": ^7.7.2
  "@formkit/addons": ^1.7.2
  "@formkit/core": ^1.7.2
  "@formkit/drag-and-drop": ^0.5.3
  "@formkit/i18n": ^1.7.2
  "@formkit/inputs": ^1.7.2
  "@formkit/vue": ^1.7.2
  "@primeuix/themes": ^2.0.3
  "@types/fs-extra": ^11.0.4
  "@types/node": ^24.12.0
  "@unocss/preset-icons": ^66.6.2
  "@unocss/preset-uno": ^66.6.2
  "@vitejs/plugin-vue": ^6.0.5
  "@vue/compiler-sfc": ^3.5.30
  "@vue/server-renderer": ^3.5.30
  "@vue/tsconfig": ^0.8.1
  "@vueuse/core": ^14.2.1
  "@vueuse/head": ^2.0.0
  add: ^2.0.6
  chart.js: ^4.5.1
  consola: ^3.4.2
  cookie: ^1.1.1
  esbuild: ^0.27.4
  eslint: ^10.0.3
  fs-extra: ^11.3.4
  happy-dom: ^20.8.4
  json-editor-vue: ^0.18.1
  primeicons: ^7.0.0
  primevue: ^4.5.4
  sass: ^1.98.0
  tsconfig: ^7.0.0
  tsdown: ^0.21.2
  tslib: ^2.8.1
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.6.7
  unplugin-auto-import: ^21.0.0
  unplugin-vue: ^7.1.1
  unplugin-vue-components: ^31.0.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-dts: ^4.5.4
  vite-plugin-eslint: ^1.8.1
  vite-plugin-pages: ^0.33.3
  vite-plus: ^0.1.14
  vite-ssg: ^28.3.0
  vitepress: 2.0.0-alpha.16
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.31
  vue-demi: ^0.14.10
  vue-i18n: ^11.3.0
  vue-router: ^5.0.3
  vue-sfc-transformer: ^0.1.17
  vue-tsc: ^3.2.6

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
