minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

overrides:
  '@openuxkit/styled': ^1.0.0
  '@openuxkit/styles': ^1.0.0
  '@openvue/themes': 1.0.0
  '@openuxkit/utils': ^1.0.0
  '@openvue/core': 1.0.0
  '@openvue/icons': 1.0.0
  primeicons: 7.0.0
  openvue: 1.0.0

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  json-editor-vue: false
  vue-demi: false
