/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    PrimeEditor: typeof import('./components/demo/PrimeEditor.vue')['default']
    PrimeEditorInput: typeof import('./components/demo/PrimeEditorInput.vue')['default']
    PrimeInput: typeof import('./components/demo/PrimeInput.vue')['default']
    PrimeOutput: typeof import('./components/demo/PrimeOutput.vue')['default']
    PrimeSchemaEditor: typeof import('./components/demo/PrimeSchemaEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
