/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from "vue";

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    PrimeData: typeof import('./components/demo/PrimeData.vue')['default']
    PrimeInput: typeof import('./components/demo/PrimeInput.vue')['default']
    PrimeLabel: typeof import('./components/demo/PrimeLabel.vue')['default']
    PrimeOutput: typeof import('./components/demo/PrimeOutput.vue')['default']
    PrimeSchemaEditor: typeof import('./components/demo/PrimeSchemaEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppFooter: (typeof import("./components/app/AppFooter.vue"))["default"];
  const AppTopbar: (typeof import("./components/app/AppTopbar.vue"))["default"];
  const PrimeData: (typeof import("./components/demo/PrimeData.vue"))["default"];
  const PrimeInput: (typeof import("./components/demo/PrimeInput.vue"))["default"];
  const PrimeLabel: (typeof import("./components/demo/PrimeLabel.vue"))["default"];
  const PrimeOutput: (typeof import("./components/demo/PrimeOutput.vue"))["default"];
  const PrimeSchemaEditor: (typeof import("./components/demo/PrimeSchemaEditor.vue"))["default"];
  const RouterLink: (typeof import("vue-router"))["RouterLink"];
  const RouterView: (typeof import("vue-router"))["RouterView"];
}
