// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    PrimeCheckBox: typeof import('./components/PrimeCheckBox.vue')['default']
    PrimeEditor: typeof import('./components/PrimeEditor.vue')['default']
    PrimeInputText: typeof import('./components/PrimeInputText.vue')['default']
    PrimeInputTextArea: typeof import('./components/PrimeInputTextArea.vue')['default']
  }
}

export { }
